#!/bin/bash

set -e

g++ -o test -std=c++14 -O2 -march=native src/test.cpp src/Lexer.cpp src/Rules.cpp src/SyntaxNode.cpp src/Parse.cpp -Isrc -lmingw32 -static
mv test.exe bin/test.exe
./bin/test.exe
